
[viner]
	#Maximum number of blocks to vein mine
	#Range: > 1
	vineableLimit = 5
	#List of blocks/tags that can be vein mined. Tags must start with '#'
	vineableBlocks = ["#minecraft:ores", "#minecraft:logs", "#minecraft:leaves", "#forge:ores", "minecraft:skulk"]
	#List of blocks that will not vein mined. This will override blocks from tags in VINEABLE_BLOCKS
	unvineableBlocks = []

